server:
  port: 8085

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8080
          predicates:
            - Path=/users/**
        - id: auth-signup
          uri: http://localhost:8080
          predicates:
            - Path=/auth/signup
          filters:
            - RewritePath=/auth/signup, /users
        - id: auth-login
          uri: http://localhost:8085
          predicates:
            - Path=/auth/login
        - id: project-service
          uri: http://localhost:8081
          predicates:
            - Path=/projects/**
        - id: task-service
          uri: http://localhost:8082
          predicates:
            - Path=/tasks/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG